version: '3.6'
services:
  # app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile.dev
  #   command: sh -c 'npm prune && npm install && npm run start:dev'
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./app:/app
  #   depends_on:
  #     - 'api'

  db:
    image: postgis/postgis:11-3.1-alpine
    command: postgres -c stats_temp_directory=/tmp
    restart: always
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dms_dev
      POSTGRES_PASSWORD: dms_dev
      POSTGRES_DB: dms_dev
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
    depends_on:
      - 'db'
