FROM python:3.8-slim-buster

# set work directory
WORKDIR /api

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

ENV FLASK_APP="dms.py"

ENTRYPOINT ["/api/entrypoint.sh"]
