FROM python:3.8-slim-buster

# set work directory
WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

# # set environment variables
# ENV PYTHONDONTWRITEBYTECODE 1
# ENV PYTHONUNBUFFERED 1


# COPY ./requirements.txt /usr/src/app/requirements.txt
# RUN pip install -r requirements.txt

# # copy project
# COPY . /usr/src/app/

# # run entrypoint.sh
ENV FLASK_APP="dms.py"

ENTRYPOINT ["/app/entrypoint.sh"]
